# Generated by Django 3.1.7 on 2021-02-24 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='user_id',
            new_name='chat_user_id',
        ),
        migrations.RenameField(
            model_name='chat',
            old_name='user_name',
            new_name='chat_user_name',
        ),
        migrations.AlterUniqueTogether(
            name='chat',
            unique_together={('meeting_id', 'chat_user_name'), ('meeting_id', 'chat_user_id')},
        ),
    ]
