# Generated by Django 3.1.7 on 2021-02-24 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210224_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='meeting_id',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='chat',
            unique_together=set(),
        ),
    ]
