# Generated by Django 3.1.7 on 2021-03-17 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_chat_callback_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='internal_meeting_id',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
    ]
